### ISSUE TITLE
Installer crash when trying to install with Wine under linux

### ISSUE THREAD

**Issue by jwallden** [Thwargle/ThwargLauncher#3]
Hello!

I know that this may be a little out of scope but I'm trying to get the AC client with ThwargLauncher and Decal going under Linux (tested Ubuntu 17.10 and Mint 18.2 and Wine 2.0.2 stable and 2.16 development). AC client installs just fine and seems to be runnable (at least I got the login screen). Decal also installs and runs. However, ThwargLaucher does not. The installer crashes on me with a [SEH_AV_READ_NULLPTR] ACCESS_VIOLATION (...) error. From what I can tell this is the Advanced Installer crashing. So I was wondering if you would be willing to upgrade the installer to some later (latest?) version to see if that works better and we can get things going on Linux? (or, are there other options for installing the launcher?)

Thank you!

**Comment by Thwargle** [comment]
If you're trying to get this to work on linux; I would suggest you bypass the installer altogether. It's a portable application, but it's also WPF, so it's very dependant on windows libraries. I have never tried to get it to work on linux, but I'm not saying it's impossible. I would suggest you compile source (or install it on a windows machine and take the installed files over).
