### ISSUE TITLE
ThwargLauncher doesn't run on Windows XP

### ISSUE THREAD

**Issue by matt-riemer** [Thwargle/ThwargLauncher#5]
Hey,

I recently tried to install ThwargLauncher on Windows XP 32-bit SP3 (lol, I know).

As per the instructions over at https://www.gdleac.com/

When I run the launcher.exe, I get the error "This is not a valid win32 application", however the updater.exe works just fine.

I think you probably don't want to support Windows XP, but thought you might want to document that it's not supported.

Thanks so much!

**Comment by Thwargle** [comment]
That's a depricated OS and I don't think it's necessary to list that as unsupported on modern software. The launcher uses .net 4.5 which is too new for XP.
